import store from "@/store";
import "../styles/globals.css";
import ClientProviders from "./ClientProviders";

export const metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "Invexis",
  description: "An Inventory Management System",
>>>>>>> master
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
